[package]
name = "program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "0.10.3"
borsh-derive = "0.10.3"
solana-program = "1.15.2"
state-interface = { path = "../interface", version = "0.1.0" }
